services:
  app:
    image: ghcr.io/gooley/storybook:latest
    restart: unless-stopped
    ports:
    - "3000:3000"
    env_file:
    - .env
    environment:
    - NODE_ENV=production
    - DATA_DIR=/app/data
    volumes:
    - storybook-data:/app/data
volumes:
  storybook-data: null
